char *ERRMSG[] = {
"Unable to open socket to determine 6to4 addr\n",
"ioctl failed\n",
"fragement isn't long enough\n",
"not a udp fragement\n",
"offset: %d, more %d\n",
"failed to send to remote host\n",
"removing old child\n",
"Wrong ip6 length\n",
"Wrong UDP port\n",
"Wrong UDP length, %d != %d\n",
"send %d to child\n",
"remove child\n",
"child creation calloc failed\n",
"invalid client src ip\n",
"invalid packet length %d for ipv6 header\n",
"invalid packet length %d (%d) for ipv6 payload\n",
"invalid dst addr\n",
"done...byebye\n",
"removing idle child\n",
};
